In [1]:
import pandas as pd

# Importation des donées de services

In [2]:
df_p_s = pd.read_excel("C:/Users/testa/Documents/Zalya_Stage/DATA/REEL DATA.xlsx", sheet_name = "Services-Produits")

## Analyse exploratoire

In [3]:
df_p_s.head()

   N°                      Produits /Services
0   1                          Conception web
1   2  Développement plateformes ou logiciels
2   3                  Communication digitale
3   4                              Imprimerie
4   5                              Imporation

In [4]:
df_p_s.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   N°                  10 non-null     int64
 1   Produits /Services  10 non-null     str
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

In [5]:
df_p_s.columns = df_p_s.columns.str.strip()
df_p_s["Produits /Services"] = (
    df_p_s["Produits /Services"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [6]:
df_p_s.head()

   N°                      Produits /Services
0   1                          conception web
1   2  développement plateformes ou logiciels
2   3                  communication digitale
3   4                              imprimerie
4   5                              imporation

In [7]:
df_p_s.describe

<bound method NDFrame.describe of    N°                                 Produits /Services
0   1                                     conception web
1   2             développement plateformes ou logiciels
2   3                             communication digitale
3   4                                         imprimerie
4   5                                         imporation
5   6                         gestion et vente des biens
6   7  prestations industrielles ( climatisation et f...
7   8                    mise à disposition du personnel
8   9                                gestion de sécurité
9  10                   formation présentiel et en ligne>

In [8]:
print(df_p_s.duplicated().sum())

0

### Prétraitement des données

In [9]:
df_p_s.rename(
    columns={
        "Produits /Services":
        "nom_service"
    },
    inplace=True
)

In [10]:
df_p_s["service_id"] = range(
    1,
    len(df_p_s) + 1
)

In [11]:
df_p_s.head()

   N°                             nom_service  service_id
0   1                          conception web           1
1   2  développement plateformes ou logiciels           2
2   3                  communication digitale           3
3   4                              imprimerie           4
4   5                              imporation           5

#### Ajout d'une colonne catégorie

In [12]:
categories = {

    "conception web": "digital",

    "développement plateformes ou logiciels":
    "digital",

    "communication digitale":
    "marketing",

    "imprimerie":
    "print_media",

    "imporation":
    "logistique",

    "gestion et vente des biens":
    "commerce",

    "prestations industrielles ( climatisation et froid, maintenance industrielle, peinture,l'électricité)":
    "industrie",

    "mise à disposition du personnel":
    "rh",

    "gestion de sécurité":
    "securite",

    "formation présentiel et en ligne":
    "formation"
}

In [13]:
df_p_s["categorie"] = (
    df_p_s["nom_service"]
    .map(categories)
)

In [14]:
df_p_s.head()

   N°                             nom_service  service_id    categorie
0   1                          conception web           1      digital
1   2  développement plateformes ou logiciels           2      digital
2   3                  communication digitale           3    marketing
3   4                              imprimerie           4  print_media
4   5                              imporation           5   logistique

In [15]:
df_p_s["actif"] = True

In [16]:
df_p_s["prix_reference"] = None
df_p_s["cout_estime"] = None
df_p_s["marge_estimee"] = None

In [17]:
df_p_s.head()

,N°,nom_service,service_id,categorie,actif,prix_reference,cout_estime,marge_estimee
0,1,conception web,1,digital,True,None,None,None
1,2,développement plateformes ou logiciels,2,digital,True,None,None,None
2,3,communication digitale,3,marketing,True,None,None,None
3,4,imprimerie,4,print_media,True,None,None,None
4,5,imporation,5,logistique,True,None,None,None

In [18]:
df_p_s= df_p_s.drop("N°",axis= 1)

In [19]:
df_p_s.head()

,nom_service,service_id,categorie,actif,prix_reference,cout_estime,marge_estimee
0,conception web,1,digital,True,None,None,None
1,développement plateformes ou logiciels,2,digital,True,None,None,None
2,communication digitale,3,marketing,True,None,None,None
3,imprimerie,4,print_media,True,None,None,None
4,imporation,5,logistique,True,None,None,None

In [22]:
df_p_s["nom_service"]= df_p_s["nom_service"].replace({
    "communication digitale": "communication",
    "imporation": "importation",
})

In [23]:
df_p_s

,nom_service,service_id,categorie,actif,prix_reference,cout_estime,marge_estimee
0,conception web,1,digital,True,None,None,None
1,développement plateformes ou logiciels,2,digital,True,None,None,None
2,communication,3,marketing,True,None,None,None
3,imprimerie,4,print_media,True,None,None,None
4,importation,5,logistique,True,None,None,None
5,gestion et vente des biens,6,commerce,True,None,None,None
6,prestations industrielles ( climatisation et f...,7,industrie,True,None,None,None
7,mise à disposition du personnel,8,rh,True,None,None,None
8,gestion de sécurité,9,securite,True,None,None,None
9,formation présentiel et en ligne,10,formation,True,None,None,None

In [27]:
df_p_s["prix_reference"] = (
    df_p_s["prix_reference"]
    .fillna(0)
)
df_p_s["cout_estime"] = (
    df_p_s["cout_estime"]
    .fillna(0)
)
df_p_s["marge_estimee"] = (
    df_p_s["marge_estimee"]
    .fillna(0)
)

In [28]:
df_p_s

,nom_service,service_id,categorie,actif,prix_reference,cout_estime,marge_estimee
0,conception web,1,digital,True,0,0,0
1,développement plateformes ou logiciels,2,digital,True,0,0,0
2,communication,3,marketing,True,0,0,0
3,imprimerie,4,print_media,True,0,0,0
4,importation,5,logistique,True,0,0,0
5,gestion et vente des biens,6,commerce,True,0,0,0
6,prestations industrielles ( climatisation et f...,7,industrie,True,0,0,0
7,mise à disposition du personnel,8,rh,True,0,0,0
8,gestion de sécurité,9,securite,True,0,0,0
9,formation présentiel et en ligne,10,formation,True,0,0,0

In [30]:
### exportation du dataset nettoyé 
df_p_s.to_csv("services_clean.csv", index = False)